name: latihan aws cli

on:
  push:
    branches:
        - main
env:
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
  AWS_REGION: ${{ secrets.AWS_REGION }}
  EB_ENV_NAME: ${{ secrets.EB_ENV_NAME }}
  EB_PLATFORM_NAME: ${{secrets.EB_PLATFORM_NAME}}
  S3_BUCKET_NAME: ${{ secrets.S3_BUCKET_NAME }}
  EB_DNS_NAME: ${{secrets.EB_DNS_NAME}}

jobs:
    build: 
        runs-on: ubuntu-latest

        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Set up Node.js
          uses: actions/setup-node@v3
        
        - name: Install dependencies
          run: |
            npm install
            npm install -g pm2
            npm ci

        - name: Build zip
          run: zip -r showipjs.zip . -x "node_modules/*"

        - name: Verify ZIP Contents
          run: unzip -l showipjs.zip  # Pastikan file utama ada

        - name: Upload build artifact
          uses: actions/upload-artifact@v4
          with:
            name: showipjs
            path: showipjs.zip
        
        - name: Configure AWS CLI
          run: |
            aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
            aws configure set region ${{ secrets.AWS_REGION }}

        - name: Upload to S3
          run: |
            aws s3 cp showipjs.zip s3://${{ secrets.S3_BUCKET_NAME }}/showipjs.zip
        env:
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
            AWS_REGION: ${{ secrets.AWS_REGION }}


    deploy:
        needs: build
        runs-on: ubuntu-latest
        steps:
         - name: Checkout
           uses: actions/checkout@v3

         - name: Setup AWS CLI
           run: |
             sudo apt update
             sudo apt install -y awscli

         - name: Configure AWS CLI
           run: |
                aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
                aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                aws configure set aws_session_token ${{ secrets.AWS_SESSION_TOKEN }}
                aws configure set region ${{ secrets.AWS_REGION }}

         - name: Install Elastic Beanstalk CLI
           run: |
              pip install awsebcli --upgrade
            

         - name: Set Platform EB
           run: |
            eb init -p "Node.js 22" ${{ secrets.EB_APP_NAME }} --region ${{ secrets.AWS_REGION }}

         - name: Create Enviroment
           run: |
              eb create ${{ secrets.EB_ENV_NAME }} --service-role LabRole --sample